In [1]:
import numpy as np
from datetime import datetime, timezone

In [37]:
# make a start date
start_date = "2025-10-9"

In [38]:
# length in the number of candles
length = 330

In [39]:
interval = "hourly"  # could be "hourly" or "minute"

if interval == "daily":
    step = 86400
elif interval == "hourly":
    step = 3600
elif interval == "minute":
    step = 60

In [40]:
dt = datetime.strptime(start_date, "%Y-%m-%d")
start = int(dt.replace(tzinfo=timezone.utc).timestamp())
dates = np.array([start + step * i for i in range(length)])

In [41]:
start

1759968000

In [42]:
# show dates as datetime for verification
[datetime.fromtimestamp(date, tz=timezone.utc) for date in dates]

[datetime.datetime(2025, 10, 9, 0, 0, tzinfo=datetime.timezone.utc),
 datetime.datetime(2025, 10, 9, 1, 0, tzinfo=datetime.timezone.utc),
 datetime.datetime(2025, 10, 9, 2, 0, tzinfo=datetime.timezone.utc),
 datetime.datetime(2025, 10, 9, 3, 0, tzinfo=datetime.timezone.utc),
 datetime.datetime(2025, 10, 9, 4, 0, tzinfo=datetime.timezone.utc),
 datetime.datetime(2025, 10, 9, 5, 0, tzinfo=datetime.timezone.utc),
 datetime.datetime(2025, 10, 9, 6, 0, tzinfo=datetime.timezone.utc),
 datetime.datetime(2025, 10, 9, 7, 0, tzinfo=datetime.timezone.utc),
 datetime.datetime(2025, 10, 9, 8, 0, tzinfo=datetime.timezone.utc),
 datetime.datetime(2025, 10, 9, 9, 0, tzinfo=datetime.timezone.utc),
 datetime.datetime(2025, 10, 9, 10, 0, tzinfo=datetime.timezone.utc),
 datetime.datetime(2025, 10, 9, 11, 0, tzinfo=datetime.timezone.utc),
 datetime.datetime(2025, 10, 9, 12, 0, tzinfo=datetime.timezone.utc),
 datetime.datetime(2025, 10, 9, 13, 0, tzinfo=datetime.timezone.utc),
 datetime.datetime(2025, 10, 9

In [43]:
weekdays = np.array([
    datetime.fromtimestamp(ts, tz=timezone.utc).weekday() for ts in dates])

In [44]:
weekdays

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

# Weekend starts

In [45]:
np.where((weekdays[:-1] < 5) & (weekdays[1:] >= 5))[0] + 1

array([ 48, 216])

In [47]:
weekdays[0:49]

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 5])

In [ ]:
weekdays[0:49]

In [50]:
np.where(weekdays < 1)

(array([ 96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108,
        109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 264, 265,
        266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278,
        279, 280, 281, 282, 283, 284, 285, 286, 287]),)

# Trading hours starts

Remember, this is for making test code.  This code will take artificial series and shift time at normally occuring gap areas.<br>
This will be used to create gapped series' for testing my application.